Gui
filipe-silva-27/ES-2023-2Sem-Sexta-Feira-LIGE-GrupoA pull request #3
Opened 2023-04-07 18:02 UTC by filipe-silva-27

2023-04-07 18:29 UTC, kreativermario approved these changes
Parece-me tudo bem exceto o Botão Voltar que dá um index out of bounds exception.

2023-04-07 18:29 UTC, kreativermario commented on src/java/gui/GUI.java
> +    private void setButtons() {
Este método não é muito legível com tantas classes anónimas

2023-04-07 19:05 UTC, fouto0 approved these changes

2023-04-08 13:52 UTC, fmrva1 approved these changes

2023-04-08 13:58 UTC, Ruisth23 approved these changes
Aprovado com sucesso!

2023-04-08 14:03 UTC, Ruisth23 approved these changes

2023-04-08 14:14 UTC, kreativermario commented
![](https://github.trello.services/images/mini-trello-icon.png) [GUI de Interação com utilizador final](https://trello.com/c/HTpiYT6n/47-gui-de-intera%C3%A7%C3%A3o-com-utilizador-final)

2023-04-08 14:18 UTC, kreativermario requested changes
Botão voltar não funciona (bug).

2023-04-08 15:42 UTC, kreativermario requested changes
A mudança do compiler source do maven não aprovo

2023-04-08 15:42 UTC, kreativermario commented on pom.xml
> +    <maven.compiler.source>20</maven.compiler.source>
Esta alteração não é ideal.

2023-04-09 15:53 UTC, kreativermario approved these changes
Aprovado

2023-04-09 18:57 UTC, kreativermario requested changes
Código muito confuso para manutenção

2023-04-12 12:00 UTC, kreativermario approved these changes
Só falta os models da GUI seguindo o MVC

2023-04-14 10:52 UTC, merged